USE [VENDAS SUCOS]
GO

/****** Object:  Table [dbo].[ITENS VENDIDOS]    Script Date: 01/06/2022 07:03:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ITENS VENDIDOS](
	[NÚMERO] [varchar](5) NOT NULL,
	[CÓDIGO PRODUTO] [varchar](10) NULL,
	[QUANTIDADE] [int] NULL,
	[PREÇO] [float] NULL,
 CONSTRAINT [PK_ITENS_VENDIDOS] PRIMARY KEY CLUSTERED 
(
	[NÚMERO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ITENS VENDIDOS]  WITH CHECK ADD  CONSTRAINT [FK_ITENS_VENDIDOS_NOTAS] FOREIGN KEY([NÚMERO])
REFERENCES [dbo].[NOTAS] ([NÚMERO])
GO

ALTER TABLE [dbo].[ITENS VENDIDOS]  WITH CHECK ADD  CONSTRAINT [FK_ITENS_VENDIDOS_PRODUTOS] FOREIGN KEY([CÓDIGO PRODUTO])
REFERENCES [dbo].[PRODUTOS] ([CÓDIGO])
GO

ALTER TABLE [dbo].[ITENS VENDIDOS] CHECK CONSTRAINT [FK_ITENS_VENDIDOS_NOTAS]
GO

ALTER TABLE [dbo].[ITENS VENDIDOS] CHECK CONSTRAINT [FK_ITENS_VENDIDOS_PRODUTOS]
GO
