ALTER TABLE [NOTAS] WITH CHECK ADD CONSTRAINT [PK_NOTAS]
PRIMARY KEY CLUSTERED ([NÚMERO])

ALTER TABLE [NOTAS] WITH CHECK ADD CONSTRAINT [FK_NOTAS_CLIENTES]
FOREIGN KEY([CPF]) REFERENCES [CLIENTES] ([CPF])

